# CloudWatch Datasource 정의 추가
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: CloudWatch
        uid: CloudWatch
        type: cloudwatch
        access: proxy
        isDefault: true
        jsonData:
          authType: ec2_iam_role
          defaultRegion: ap-northeast-2

# 대시보드 자동 로드 및 패널 정의
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    news-subscribe-dashboard:
      json: |
        {
          "title": "NewsSubscribe Monitoring Dashboard",
          "time": { "from": "now-6h", "to": "now" },
          "panels": [
            {
              "type": "timeseries",
              "title": "RDS Replica Lag (s)",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "metricName": "ReplicaLag",
                  "namespace": "AWS/RDS",
                  "dimensions": { "DBInstanceIdentifier": "news-rds" },
                  "region": "ap-northeast-2",
                  "stat": "Maximum",
                  "period": 60,
                  "refId": "RDS_ReplicaLag"
                }
              ]
            },
            {
              "type": "stat",
              "title": "Lambda Errors - sending_news",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "metricName": "Errors",
                  "namespace": "AWS/Lambda",
                  "dimensions": { "FunctionName": "news-lambda-handler" },
                  "region": "ap-northeast-2",
                  "stat": "Sum",
                  "period": 60,
                  "refId": "LambdaErr_sending"
                }
              ]
            },
            {
              "type": "stat",
              "title": "메일 전송 성공",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "expression": "SEARCH('{/aws/lambda/news-lambda-handler} \"메일 전송 성공\"', 'Count', 60)",
                  "refId": "MailOK_sending",
                  "region": "ap-northeast-2"
                }
              ]
            },
            {
              "type": "stat",
              "title": "메일 전송 실패",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "expression": "SEARCH('{/aws/lambda/news-lambda-handler} \"메일 전송 실패\"', 'Count', 60)",
                  "refId": "MailErr_sending",
                  "region": "ap-northeast-2"
                }
              ]
            },
            {
              "type": "stat",
              "title": "Lambda Errors - crawler",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "metricName": "Errors",
                  "namespace": "AWS/Lambda",
                  "dimensions": { "FunctionName": "news-crawler-lambda" },
                  "region": "ap-northeast-2",
                  "stat": "Sum",
                  "period": 60,
                  "refId": "LambdaErr_crawler"
                }
              ]
            },
            {
              "type": "stat",
              "title": "크롤링 성공",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "expression": "SEARCH('{/aws/lambda/news-crawler-lambda} \"크롤링 성공\"', 'Count', 60)",
                  "refId": "CrawlOK",
                  "region": "ap-northeast-2"
                }
              ]
            },
            {
              "type": "stat",
              "title": "크롤링 삭제",
              "datasource": "CloudWatch",
              "targets": [
                {
                  "expression": "SEARCH('{/aws/lambda/news-crawler-lambda} \"크롤링 삭제\"', 'Count', 60)",
                  "refId": "CrawlDel",
                  "region": "ap-northeast-2"
                }
              ]
            }
          ]
        }
    kubelet-dashboard:
      json: |
        ${kubelet_json}
