name: Terraform Apply

on:
  push:
    branches: [main]

jobs:
  apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev

    steps:
      - uses: actions/checkout@v4

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Generate tfvars from secrets
        run: |
          echo 'db_password = "${{ secrets.DB_PASSWORD }}"' > terraform.auto.tfvars

      - name: Terraform Init
        run: terraform init -reconfigure -input=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

