name: Update GitHub Secret

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Output
        id: tf_output
        run: |
          cd terraform
          terraform init -input=false
          terraform output -raw rds_endpoint > endpoint.txt
          echo "RDS_ENDPOINT=$(cat endpoint.txt)" >> $GITHUB_ENV

      - name: Update GitHub Secret
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh secret set DB_HOST -b"$RDS_ENDPOINT" -R <owner>/<repo>
